Overhaul inventory handling
maximusunc/AardwolfMUDClient pull request #12
Opened 2021-02-14 19:49 UTC by patrickkwang

2021-02-15 22:57 UTC, maximusunc requested changes

2021-02-15 22:57 UTC, maximusunc commented on README.md
> +invmon
I believe invmon needs to be set at the very start of a session? In the session that I set invmon, I was getting console errors and my inventory was not working at all. I then restarted and things seemed to be working.

2021-02-15 22:57 UTC, maximusunc commented on public/global.css
> +#inventory {
These should go in the Inventory.svelte file, not global css.

2021-02-15 22:57 UTC, maximusunc commented on src/Inventory.svelte
> +<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.5/build/pure-min.css" integrity="sha384-LTIDeidl25h2dPxrB2Ekgc9c7sEC3CWGM6HeFmuDNUjX76Ert4Z4IY714dhZHPLd" crossorigin="anonymous">
I think I don't want to include any external css for this project. Was there a particular reason you wanted to include this?

2021-02-15 22:57 UTC, maximusunc commented on src/Inventory.svelte
> +        document.getElementById(`${tabName}_panel`).style.display = "block";
Is there a way to have inventory be selected by default?

2021-02-15 22:57 UTC, maximusunc commented on src/output.js
> +class DefaultMap extends Map {
Where is Map coming from?

2021-02-15 22:57 UTC, maximusunc commented on src/output.js
> +class DefaultMap extends Map {
This whole class looks like it's unused?

Ohhh, this name in context is confusing.

2021-02-15 22:57 UTC, maximusunc commented on src/output.js
> +    var containerid = "";
Let's not use var. Use let or const instead.

2021-02-15 22:57 UTC, maximusunc commented on src/output.js
> +    return msg;
extractInvmon and extractInvitem don't seem to be replacing anything in the msg. Also, they're always returning msg, so could this be if invmon is truthy, then do the thing?

2021-02-15 22:57 UTC, maximusunc commented on src/output.js
> +export { captor, strip_colors };
This file is now pretty massive. Is there a way to move the captor class out of this file and into its own?

2021-02-15 22:57 UTC, maximusunc commented on src/Inventory.svelte
> +                    <li>{@html $output.items.get(objectid).display()}</li>
Is there a way to not strip out all the colors?

2021-02-15 22:57 UTC, maximusunc commented on src/output.js
> +export { captor, strip_colors };
Also have you looked into how to display the items inside of containers (i.e. my traveller's backpack has stuff in it)?

2021-02-16 03:11 UTC, patrickkwang commented on public/global.css
> +#inventory {
I tried that, but svelte was trying to be clever and dropping rules that it didn't think I was using, but which I am. My workaround was to put them here...

2021-02-16 03:12 UTC, patrickkwang commented on src/Inventory.svelte
> +<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.5/build/pure-min.css" integrity="sha384-LTIDeidl25h2dPxrB2Ekgc9c7sEC3CWGM6HeFmuDNUjX76Ert4Z4IY714dhZHPLd" crossorigin="anonymous">
I just wanted something to make the CSS easy for me.

2021-02-16 03:14 UTC, patrickkwang commented on src/Inventory.svelte
> +        document.getElementById(`${tabName}_panel`).style.display = "block";
I don't know. I think svelte would have to assign a default when the tabs first get populated.

2021-02-16 03:14 UTC, patrickkwang commented on src/output.js
> +class DefaultMap extends Map {
I don't understand. Do you have a question or suggestion?

2021-02-16 03:16 UTC, patrickkwang commented on src/output.js
> +    return msg;
I like to keep if blocks small, and kick out early like this rather than have most of the function body inside a big if block. Also, we could strip these line out of the msg, I just haven't yet.

2021-02-16 03:17 UTC, patrickkwang commented on src/output.js
> +export { captor, strip_colors };
Yeah, we should shuffle code around. And yes, try moving something in/out of your bag.

2021-02-16 03:19 UTC, patrickkwang commented on src/Inventory.svelte
> +                    <li>{@html $output.items.get(objectid).display()}</li>
Of course. I think the colors only work well on a black background, and I didn't spend a ton of time on the styling. Just trying to get this functional for now.

2021-02-18 01:13 UTC, maximusunc commented on public/global.css
> +#inventory {
I'm skeptical.

2021-02-18 01:15 UTC, maximusunc commented on src/Inventory.svelte
> +        document.getElementById(`${tabName}_panel`).style.display = "block";
I would also say that this can all be done dynamically in svelte rather than through vanilla javascript.

2021-02-18 01:16 UTC, maximusunc commented on src/output.js
> +class DefaultMap extends Map {
I think overall, these functions and classes could use some documentation. I really like jsdocs format because then VSCode will show you your description when you hover over the function.

2021-02-18 01:19 UTC, maximusunc commented on src/output.js
> +export { captor, strip_colors };
I'm envisioning the containers in your inventory being expandable drop downs that you can click on to view everything inside it. That would be cool.

2021-02-18 01:20 UTC, maximusunc commented on src/Inventory.svelte
> +                    <li>{@html $output.items.get(objectid).display()}</li>
Ok. We can certainly play around with the styling to make it all look cool.

2021-02-18 13:58 UTC, patrickkwang commented on src/Inventory.svelte
> +        document.getElementById(`${tabName}_panel`).style.display = "block";
Do you mean all of the tab-switching logic? That would be nice.

2021-02-18 14:00 UTC, patrickkwang commented on README.md
> +invmon
It only needs to be set once, ever, but I'm not surprised that the session in which you set it could be funky.

2021-02-18 14:03 UTC, maximusunc commented on src/Inventory.svelte
> +        document.getElementById(`${tabName}_panel`).style.display = "block";
I think i understand what's going on now. You're using vanilla javascript to modify these properties, but that's outside svelte's view and is why it's also throwing out some of your css. I would convert the vanilla javascript into svelte stuff.

Up in your script tag:
`const openTab = 'inventory'`

In the html:
```
{#each [...Object.keys($output.containers)].reverse() as containerid}
{#if openTab === containerid}
// do your foreach of container contents here
{/if}
{/each}
```

Then you don't have to do any of that style.display toggling.

2021-02-18 14:10 UTC, maximusunc commented on README.md
> +invmon
There's a way of setting this property via gmcp. `config Invmon on`. I think we should try and do this for the user.

2021-02-20 14:25 UTC, patrickkwang commented on src/output.js
> +export { captor, strip_colors };
See the 'monitor' action on containers.

2021-02-20 15:17 UTC, maximusunc requested changes
I know I told you to remove the pure-css and that got rid of the nice styling. Would you be willing to give some custom css a try? Right now it's not the best looking thing. I think you can also remove the white background and black text color. I'm happy to help with the styling as well.

2021-02-20 15:17 UTC, maximusunc commented on src/Log.svelte
> +        font-size: 13px;
This is no longer needed.

2021-02-20 15:17 UTC, maximusunc commented on src/Inventory.svelte
> +    const handleRefresh = () => {
The button for this function is commented out. Do we ever need to ask for the containers?

2021-02-20 15:17 UTC, maximusunc commented on src/output.js
> +  return msg;
Can we remove all the invitem, invdata, invmon etc. lines from the log?

2021-02-20 15:17 UTC, maximusunc commented on src/output.js
> +export { captor, strip_colors };
Can we put all the inventory logic in it's own file?

2021-02-20 16:01 UTC, maximusunc commented
A few more thoughts:
- In general, the <a> tag is mean for url links, so I think the <a> tags in the inventory file should be <button>s.
- Down the line, we'll probably want some sort of confirmation before doing destructive actions like using potions or dropping items.

2021-02-21 03:02 UTC, patrickkwang commented
"tag"is the terminology used in the Aardwolf docs: http://www.aardwolf.com/wiki/index.php/Help/Invdata
Do you have other suggestions?

2021-02-21 14:51 UTC, maximusunc commented
> "tag"is the terminology used in the Aardwolf docs: http://www.aardwolf.com/wiki/index.php/Help/Invdata
> Do you have other suggestions?

That's my bad. I didn't check how my comment actually displayed. In the html, the "a" tags are generally meant for url links. Can we change those to buttons?

2021-02-21 15:09 UTC, maximusunc requested changes

2021-02-21 15:09 UTC, maximusunc commented on src/output.js
> +  items: new DefaultMap(() => new Item()),
Item is not defined.

2021-02-21 15:09 UTC, maximusunc commented on src/output.js
> +const { ipcRenderer } = require('electron');
ipcRenderer is never used.

2021-02-22 01:02 UTC, patrickkwang commented
I'm wary of spending much time on styling at this point since I don't even have a good feel for the final features, much less UX.

2021-02-22 01:06 UTC, patrickkwang commented
I still don't love how the code is organized. No, that's an understatement; I really dislike it. I suppose it's nice that bidirectional dependencies are possible, but it seems like a bad thing to rely on. Maybe I just need to think harder.

2021-02-22 14:10 UTC, maximusunc approved these changes

2021-02-22 14:10 UTC, merged