MCCP
maximusunc/AardwolfMUDClient pull request #45
Opened 2021-05-22 00:08 UTC by patrickkwang

2021-05-23 21:42 UTC, maximusunc requested changes

2021-05-23 21:42 UTC, maximusunc commented on telnet-stream/lib/telnetInput.js
> +        this.decompressor.write(chunk);
We might never run into this issue, but if there were ever an error decompressing, we should either close the telnet connection or send an `IAC DONT COMPRESS2` (i.e. tsock.writeDont(86)) to stop compression. This could be a separate issue because so far, this PR does implement mccp correctly.

2021-05-25 17:28 UTC, patrickkwang commented on main.js
> +let usingMCCP = false;
https://github.com/maximusunc/AardwolfMUDClient/pull/45/commits/9a61bb4f6012169cc95802d00e526d6a0fba26c2

2021-05-25 17:29 UTC, patrickkwang commented on telnet-stream/lib/telnetInput.js
> +        this.decompressor.write(chunk);
#46

2021-05-25 17:32 UTC, maximusunc approved these changes

2021-05-25 17:33 UTC, merged